import { Geist, Geist_Mono , Cormorant_Garamond} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en">
      <body className={cormorant.className}>
        <Providers>
     <div className="min-h-screen p-2" style={{ border: "12px solid #d8b77b", boxShadow: "inset 0 0 0 2px #fff, inset 0 0 0 6px #6b4f2a", }}>
          <Navbar />

          <main>
            {children}
            <Toaster position="top-right" />
          </main>

          <Footer />
          </div>
          </Providers>
      </body>
    </html>
  );
}
